### ISSUE TITLE
Brauchen wir einen Ordner Backwaren?

### ISSUE THREAD

**Issue by strautz** [SanJSp/Lets_git_kochbuch#19]
Bei dem Baguette war ich mir nicht sicher, ob es bei Frühstück gut aufgehoben ist. Nachher findet ihr es nicht und seid traurig.

BY THE WAY: Bei dem neuen Issue steht:
Hiermit kansnt du ein neues Rezept anfragen/vorschlagen.
            ^^^^

**Comment by strautz** [comment]
Ich hab das Label da nicht hingetan. Kommt das von selbst, weil ich "Rezept" im Text habe?

**Comment by verspaeteterZug** [comment]
fände ich definitiv eine gute Idee
