### ISSUE TITLE
Maintainer gesucht

### ISSUE THREAD

**Issue by SanJSp** [SanJSp/Lets_git_kochbuch#3]
Da ich nicht alle Probleme für mehr als 8000 Kursteilnehmer lösen kann, bräuchte ich Unterstützung beim Organisieren der Let's Git Repositories. Dabei freue ich mich über Vorschläge, wie man das alles organisieren kann und wenn sich freiwillige melden.

Bitte schlagt etwas vor oder meldet euch bereit zu helfen.

**Comment by Combot0** [comment]
Was wären denn so die typischen Aufgaben des Maintainers? 

Ich hätte als Vorschlag zur Organisation, dass ein Projekt anlegt wird, in dem man dann per Kanban Board sehen kann, in welchem Status sich die Issues befinden. Ob dieses bereits von jemanden bearbeitet wird oder noch offen ist.

**Comment by SanJSp** [comment]
Hi @Combot0

die Aufgabe eines Maintainers wäre eben solche Dinge zu verwalten. Außerdem wünsche ich mir von Maintainern, dass diese Pull Requests prüfen und dann mergen. Sozusagen möchte ich auch die Lernmöglichkiet bieten, die Führung dieses Projekts (im Team) zu übernehmen.

Hoffentlich hilft das weiter, wenn nicht gerne nachhaken.

Liebe Grüße
Sandro

**Comment by Combot0** [comment]
Hi @SanJSp 

vielen Dank für die Rückmeldung. Ich würde gern die Rolle übernehmen und so das Projekt unterstützen und mich etwas weiterzubilden 😄. 

Viele Grüße
Stefan

**Comment by SanJSp** [comment]
Ich würde noch ein zwei Tage warten, damit so eine gewisse Richtung des Projekts erkennbar ist. Dann füge ich dich hinzu :) Gerne können sich noch mehr Maintainer melden!

**Comment by Christoph-MH** [comment]
Moin Sandro,
das hört sich ziemlich interessant an und ich würde gerne mitmachen.
Ich habe allerdings noch keine Idee, wie alles organisiert werden könnte.
LG
Christoph

**Comment by ancchi** [comment]
Ich würde auch gerne mal Maintainer spielen. :)

Vorschlag zu den Issues: wäre es möglich, dass jeder der sich ein Issue nimmt, sich auch selbst als Assignee einträgt, damit klar ist, dass das Issue in Bearbeitung ist?

**Comment by SanJSp** [comment]
@ancchi 

das ist sogar empfehlenswert und sollte auch gemacht werden!

Liebe Grüße  
Sandro

**Comment by Combot0** [comment]
Ich glaube das assignen geht nur, wenn man Schreibrechte auf dem Repo hat.

**Comment by ancchi** [comment]
@Combot0, @SanJSp 
Genau. Wir können uns als "Normalis" nicht selber assignen. Deswegen meine Frage ...

**Comment by SanJSp** [comment]
Jawohl, deswegen werdet ihr 3 jetzt zu Maintaienrn ernannt! 😄
