### ISSUE TITLE
Frikadellen, vegetarisch

### ISSUE THREAD

**Issue by Ennah75** [SanJSp/Lets_git_kochbuch#35]
Ich würde gerne das Gericht bzw. Snack / Beilage "Vegetarische Frikadellen" hinzufügen. Habe ich frisch entdeckt und bereits zwei Mal gemacht. Schmeckt hervorragend, auch für nicht-Vegetarier.

**Comment by tad3u5** [comment]
Bitte erstelle in Deinem Repo einen Branch für die Vegetarischen Frikadellen und reiche sie als Pull request nochmal ein. Das Rezept hat mir gefallen. Nur das mischen mit dem Bananenbrot sollte nicht sein.
Aber das Brot kannst du auch gerne noch einreichen. 

Genau das gleiche ist mir auch passiert. Ich hatte meine Einreichung Pflaumenkuchen auf meinem Master gemacht und die zweite Einreichung Mate-Limo hat dann den Commit Pflaumenkuchen auch beinhaltet.
