### ISSUE TITLE
Tippfehler im Beispielrezept

### ISSUE THREAD

**Issue by jfkoeln** [SanJSp/Lets_git_kochbuch#4]
Im Beispielrezept  lets_git_kochbuch/Beispielrezept.md liegt ein Tippfehler beim 1. Punkt der Anleitung vor. 
Statt "Wasser zum Kocken bringen" müsste es "Wasser zum **Kochen** bringen" heißen.

**Comment by SanJSp** [comment]
Möchtest du das vielleicht schon in einem Pull Request lösen?

Liebe Grüße  
Sandro

**Comment by jfkoeln** [comment]
hab den PR erstellt, natürlich mit Link auf dieses Issue :-)
