### ISSUE TITLE
Bitte Snacks hinzufügen!

### ISSUE THREAD

**Issue by kriskak** [SanJSp/Lets_git_kochbuch#41]
Ich würde mich über einfache und gesunde Snacks für Zwischendurch freuen!

**Comment by doroGrund** [comment]
Ich erstelle ein Rezept für eine kleine Snackauswahl (Tomaten-Mozzarella-Spieße, Tomaten-Käse-Spieße, Ideen für Snacks zum Mitnehmen).

**Comment by kriskak** [comment]
Ich überlege gerade ob es nicht besser wäre jeden einzelnen Snack in einem eigenen Issue/Pullrequest zu bearbeiten da man das besser überblicken kann. 
Aber wenn du deiner Arbeit einen aussagekräftigen Titel gibst wird es passen...
