### ISSUE TITLE
Grillgerichte Kategorie fehlt

### ISSUE THREAD

**Issue by tad3u5** [SanJSp/Lets_git_kochbuch#49]
Ich schlage vor Grillgerichte noch in die Sammlung mit auf zu nehmen. Da aber nicht nur Hauptgerichte auf dem Grill zubereitet werden können, empfehle ich diese Kategorie in den Grundordner zu setzen.

**Comment by hahabl** [comment]
Sollten dann weitere Unterordner im Ordner Grillgerichte aufgeführt werden?
Wenn ja, welche?
Mit kommen da z.B. Fleisch, Gemüse, Süßes, Vegetarisches... in den Sinn.

**Comment by tad3u5** [comment]
Je nach Umfang der Abteilung sicherlich. Aber vielleicht auch immer erst nach Bedarf. Sonst haben wir zu viele leere Ordner und die Enttäuschung beim Durchstöbern der Sammlung wird zu groß.

**Comment by hjfriedrich** [comment]
Die Struktur sollte so beschaffen sein, dass die Rezepte jeweils nur einer Kategorie zugewiesen werden können. Ansonsten müsste man es ja kopieren oder es wäre nicht in jeder zutreffenden Kategorie enthalten. Ein Rindersteak würde in Grillgerichte und in Hauptgerichte passen. Möchte man Rezepte nach ihren Eigenschaften wie der Zubereitungsart kategorisieren, wäre es vielleicht sinnvoller, dafür Labels einzusetzen. Dann bliebe das Rindersteak ein Hauptgericht und erhielte das Label Grillgericht.
