### ISSUE TITLE
Tippfehler in README.md

### ISSUE THREAD

**Issue by verspaeteterZug** [SanJSp/Lets_git_kochbuch#5]
In der README.md gibt es einen kleinen Tippfehler. Ich denke das "Markdwon" soll "Markdown" heißen.

**Comment by verspaeteterZug** [comment]
Dann ändere ich das jetzt

**Comment by verspaeteterZug** [comment]
Ich hatte das Problem, dass beim Versuch, die Änderungen zu Uploaden diese Fehlermeldung kam:
`$ git push origin Fix_Tippfehler_behoben

remote: Permission to SanJSp/lets_git_kochbuch.git denied to BS-scripter.

fatal: unable to access 'https://github.com/SanJSp/lets_git_kochbuch.git/': The requested URL returned error: 403 `

**Comment by SanJSp** [comment]
Hallo @BS-scripter 

du musst das Repository forken und dann dort bearbeiten. DAnn kansnt du die Änderungen hier vorschlagen.

Liebe Grüße   
Sandro

**Comment by strautz** [comment]
Dann ändere doch gleich diese Fehler mit:
Wie läuft ein Pull Request Review?

Da ich nicht alle Rezepte ausführlich durchlesen kann, ist jeder Pull Request Review willkommen, um Rechtschreibfehler und mehr zu erkennen. Ich werde dann deine Einreich**_ung_** mergen.
Maintainer gesucht

Ich kann hier nicht über alle Let's Git Repositories alles überblicken, weswegen ich mich freuen würde_**,**_ wenn wir bis zu 5 Maintainer für dieses Projekt finden. Gerne kann dafür in einem Issue diskutiert werden.
