### ISSUE TITLE
Walnuss-Brownies hinzufügen

### ISSUE THREAD

**Issue by ClaudiaGrau** [SanJSp/Lets_git_kochbuch#59]
Wie lautet der Name des Gerichts?
Walnuss-Brownies

Warum möchtest du es hinzufügen?
Ich habe es heute gebacken und es war sehr lecker. Darum möchte ich es gern mit anderen Teilen.

In welche Gruppe von Gerichten gehört es? (Salate, Frühstück, ...)
Desserts/Kuchen

**Comment by tad3u5** [comment]
Sehr gerne darfst du dieses Rezept mit uns teilen. Vielleicht hast du ja noch ein Foto, wenn vom Brownie noch was übrig ist. Ich freue mich auf deinen Pull request.

**Comment by ClaudiaGrau** [comment]
Issue ist jetzt als Pull request eingereicht. Ich bin gespannt, ob es funktioniert hat.
