### ISSUE TITLE
Tippfehler Ordnername "Deserts\Kuchen"

### ISSUE THREAD

**Issue by doroGrund** [SanJSp/Lets_git_kochbuch#7]
Der Ordnername müsste auf "Des**s**erts\Kuchen" geändert werden.

**Comment by SanJSp** [comment]
Hallo @doroGrund 

kansnt du dafür vielleicht einen Pull Request erstellen?

Liebe Grüße   
Sandro

**Comment by oresch** [comment]
Ich würde das Issue bearbeiten. Ist vlt sonst jemand dran?
