### ISSUE TITLE
Zwei Ordner mit Deserts

### ISSUE THREAD

**Issue by Combot0** [SanJSp/Lets_git_kochbuch#75]
Hi, ich habe gesehen, dass wir zwei Ordner mit Deserts haben im Hauptverzeichnis. Kann jemand diese vielleicht in einen Ordner zusammenfassen?

**Comment by highdynamic** [comment]
Ich werden den Fehler beheben.

**Comment by highdynamic** [comment]
Issue ist abgeschlossen und kann geschlossen werden 👍

**Comment by Combot0** [comment]
Vielen Dank
