### ISSUE TITLE
Cocktail Rezept (Darjeeling Lazy Afternoon Lemonade) hinzufügen

### ISSUE THREAD

**Issue by katrine-github** [SanJSp/Lets_git_kochbuch#77]
Wie lautet der Name des Gerichts?
Darjeeling Lazy Afternoon Lemonade

Warum möchtest du es hinzufügen?
Um einen Lazy Afternoon angemessen zelebrieren zu können.

In welche Gruppe von Gerichten gehört es? (Salate, Frühstück, ...)
Getränke/Cocktails

**Comment by Combot0** [comment]
Hi @katrine-github, kann der Issue geschlossen werden oder muss noch etwas gemacht werden?

**Comment by katrine-github** [comment]
Ja, ich schließe das Issu, da der Cocktail gemerged wurde und bereit ist zum genießen. Cheers!
