### ISSUE TITLE
Nusslebkuchen möchte ich beitragen

### ISSUE THREAD

**Issue by opayogi** [SanJSp/Lets_git_kochbuch#8]
Als eingefleischter Kuchenfresser möchte ich ein Rezept meiner Frau zufügen:
Gabi's Nusslebkuchen

**Comment by opayogi** [comment]
Hallo, was bedeutet das, dass ich assigned bin?
Ich verstehe das nicht, muss ich was tun?

**Comment by tad3u5** [comment]
Nein, alles in Ordnung. Mittlerweile haben wir drei Maintainer, die die Macht haben Leuten ein Issue zu zu weisen. Aber da das eh dein Issue, deine Aufgabe / Anfrage ist bleibt alles wie es ist. Ob ein Assignees besondere Rechte hat weiß ich allerdings auch nicht. Zumindest wird jetzt für jeden Dargestellt, dass sich um dieses Issue schon jemand kümmert und wer das ist.
