### ISSUE TITLE
Bilder zentral speichern/aufbewahren

### ISSUE THREAD

**Issue by Orcana01** [SanJSp/Lets_git_kochbuch#81]
**Ziel des Issue:**
Um eine gewisse Übersichtlichkeit zu gewähren sollen die Bilder (so wie in der Praxis üblich) an einem zentralen Ort gespeichert werden.

**Vorgang:**
- [ ] **Ein** Bild in den Ordner ***Images*** verschieben
- [ ] Im zugehörigen Rezept den Pfad zum Einbetten des Bildes anpassen

**weitere Informationen:**
* Der Code zum Einbinden des Bildes findet sich in: images_readme.md

**Betroffene Dateien** (Standard)
Anzahl: [3]
1. *.md des Rezeptes
2. Ordner ***Images*** enthält eine neue Datei
3. An ursprünglichen Speicherort des Bildes fehlt die entsprechende Datei

**Comment by SanJSp** [comment]
Finde ich eine gute Idee :)

**Comment by Combot0** [comment]
Ich finde diese Idee auch gut. So ein zentraler Ordner für Bilder sorgt für mehr Überblick.

**Comment by ancchi** [comment]
Find ich auch gut. Mach ich mal.

**Comment by Orcana01** [comment]
@ancchi: 
Finde ich klasse <3 Ich danke Dir (bin selber leider total "Land-unter")

Vielleicht fällt Dir ja auch eine Idee ein, wie man am besten erklärt, wie der Code zum "korrekten" einbinden aussieht ;-) 

Ich meine damit z.B. 
        img src="../../images/Kuchen.jpg"/
bzw. issue #82 

Wir hatten das Thema ja bei meinem Pull-Request zum Rotweinkuchen... Da mir allerdings noch keine Gute Beschreibung eingefallen ist, habe ich a) im Rotweinkuchen noch den "unüblichen" Befehl zum Einbetten eines Bildes und b) die image_readme noch "offen"

**Comment by ancchi** [comment]
Okay, das mit der Readme.md mach ich auch gerne. :) Ich dachte mir, dass man das am besten mit Beispielen erklärt. Freut mich, dass du das gut findest. ^^ Da das hier noch rumlag, hab ich mir das einfach mal geschnappt. :)

Tipp: wenn du das hier 
\<img src="../../images/Kuchen.jpg"/>
 in einem Kommentar einfügen willst, kannst du einfach ein Backslash davor schreiben. Dann wird es nicht als HTML interpretiert. ^^

**Comment by Orcana01** [comment]
SUPER <3 Danke Dir vor allem für den Tipp mit dem Backslash *ggg* und wieder etwas gelernt *ggg*
